-- MOVIMIENTO DE INVENTARIO RESUMIDO                                          

;WITH CALCINITINVENT( CODITEM, FECHAE,
                      CANTVEN, CANTDEV, CANTNEV, CANTDNV,
                      CANTCOM, CANTDCO, CANTNCO, CANTDNC,
                      CANTCAR, CANTDES, CANTAJU,
                      UNIDVEN, UNIDDEV, UNIDNEV, UNIDDNV,
                      UNIDCOM, UNIDDCO, UNIDNCO, UNIDDNC,
                      UNIDCAR, UNIDDES, UNIDAJU) AS
(
  SELECT O.CODITEM, O.FECHAE,
         SUM(O.CANTVEN) AS CANTVEN, SUM(O.CANTDVE) AS CANTDEV, SUM(O.CANTNEV) AS CANTNEV, SUM(O.CANTDNV) AS CANTDNV,
         SUM(O.CANTCOM) AS CANTCOM, SUM(O.CANTDCO) AS CANTDCO, SUM(O.CANTNCO) AS CANTNCO, SUM(O.CANTDNC) AS CANTDNC,
         SUM(O.CANTCAR) AS CANTCAR, SUM(O.CANTDES) AS CANTDES, SUM(O.CANTAJU) AS CANTAJU,
         SUM(O.UNIDVEN) AS UNIDVEN, SUM(O.UNIDDVE) AS UNIDDEV, SUM(O.UNIDNEV) AS UNIDNEV, SUM(O.UNIDDNV) AS UNIDDNV,
         SUM(O.UNIDCOM) AS UNIDCOM, SUM(O.UNIDDCO) AS UNIDDCO, SUM(O.UNIDNCO) AS UNIDNCO, SUM(O.UNIDDNC) AS UNIDDNC,
         SUM(O.UNIDCAR) AS UNIDCAR, SUM(O.UNIDDES) AS UNIDDES, SUM(O.UNIDAJU) AS UNIDAJU

    FROM (SELECT CODITEM,
                 SUBSTRING(CONVERT(VARCHAR,FECHAE,112),1,8) AS FECHAE,
                 SUM(IIF(TIPOFAC='A',IIF(ESUNID=0,CANTIDAD,0),0)) AS CANTVEN,
                 SUM(IIF(TIPOFAC='B',IIF(ESUNID=0,CANTIDAD,0),0)) AS CANTDVE,
                 SUM(IIF(TIPOFAC='C',IIF(ESUNID=0,CANTIDAD,0),0)) AS CANTNEV,
                 SUM(IIF(TIPOFAC='D',IIF(ESUNID=0,CANTIDAD,0),0)) AS CANTDNV,
                 0 AS CANTCOM, 0 AS CANTDCO, 0 AS CANTNCO, 0 AS CANTDNC,
                 0 AS CANTCAR, 0 AS CANTDES, 0 AS CANTAJU,

                 SUM(IIF(TIPOFAC='A',IIF(ESUNID=1,CANTIDAD,0),0)) AS UNIDVEN,
                 SUM(IIF(TIPOFAC='B',IIF(ESUNID=1,CANTIDAD,0),0)) AS UNIDDVE,
                 SUM(IIF(TIPOFAC='C',IIF(ESUNID=1,CANTIDAD,0),0)) AS UNIDNEV,
                 SUM(IIF(TIPOFAC='D',IIF(ESUNID=1,CANTIDAD,0),0)) AS UNIDDNV,
                 0 AS UNIDCOM, 0 AS UNIDDCO, 0 AS UNIDNCO, 0 AS UNIDDNC,
                 0 AS UNIDCAR, 0 AS UNIDDES, 0 AS UNIDAJU

            FROM SAITEMFAC
           WHERE (TIPOFAC IN ('A','B','C','D')) AND
                 (SUBSTRING(ISNULL(CODUBIC,''),1,LEN(+''))=+'')
           GROUP BY CODITEM,
                 SUBSTRING(CONVERT(VARCHAR,FECHAE,112),1,8)
           UNION ALL
          SELECT CODITEM,
                 SUBSTRING(CONVERT(VARCHAR,FECHAE,112),1,8) AS FECHAE,
                 0 AS CANTVEN, 0 AS CANTDVE, 0 AS CANTNEV,0 AS CANTDNV,
                 SUM(IIF(TIPOCOM='H',IIF(ESUNID=0,CANTIDAD,0),0)) AS CANTCOM,
                 SUM(IIF(TIPOCOM='I',IIF(ESUNID=0,CANTIDAD,0),0)) AS CANTDCO,
                 SUM(IIF(TIPOCOM='J',IIF(ESUNID=0,CANTIDAD,0),0)) AS CANTNCO,
                 SUM(IIF(TIPOCOM='K',IIF(ESUNID=0,CANTIDAD,0),0)) AS CANTDNC,
                 0 AS CANTCAR, 0 AS CANTDES, 0 AS CANTAJU,

                 0 AS UNIDVEN, 0 AS UNIDDVE, 0 AS UNIDNEV,0 AS UNIDDNV,
                 SUM(IIF(TIPOCOM='H',IIF(ESUNID=1,CANTIDAD,0),0)) AS UNIDCOM,
                 SUM(IIF(TIPOCOM='I',IIF(ESUNID=1,CANTIDAD,0),0)) AS UNIDDCO,
                 SUM(IIF(TIPOCOM='J',IIF(ESUNID=1,CANTIDAD,0),0)) AS UNIDNCO,
                 SUM(IIF(TIPOCOM='K',IIF(ESUNID=1,CANTIDAD,0),0)) AS UNIDDNC,
                 0 AS UNIDCAR, 0 AS UNIDDES, 0 AS UNIDAJU

            FROM SAITEMCOM
           WHERE (TIPOCOM IN ('H','I','J','K'))  AND
                 (SUBSTRING(ISNULL(CODUBIC,''),1,LEN(+''))=+'')
           GROUP BY CODITEM,
                 SUBSTRING(CONVERT(VARCHAR,FECHAE,112),1,8)
           UNION ALL
          SELECT CODITEM,
                 SUBSTRING(CONVERT(VARCHAR,FECHAE,112),1,8) AS FECHAE,
                 0 AS CANTVEN, 0 AS CANTDVE, 0 AS CANTNEV, 0 AS CANTDNV,
                 0 AS CANTCOM, 0 AS CANTDCO, 0 AS CANTNCO, 0 AS CANTDNC,
                 SUM(CASE WHEN (TIPOOPI='O') THEN IIF(ESUNID=0,CANTIDAD,0)
                          WHEN (TIPOOPI='T') THEN  IIF(ESUNID=0,CANTIDAD,0)
                                ELSE 0 END) AS CANTCAR,
                 SUM(CASE WHEN (TIPOOPI='P') THEN IIF(ESUNID=0,CANTIDAD,0)
                          WHEN (TIPOOPI='N') THEN IIF(ESUNID=0,CANTIDAD,0)
                                ELSE 0 END) AS CANTDES,
                 SUM(IIF(TIPOOPI='Q',(CANTIDAD-CANTIDADA),0)) AS CANTAJU,

                 0 AS UNIDVEN, 0 AS UNIDDVE, 0 AS UNIDNEV, 0 AS UNIDDNV,
                 0 AS UNIDCOM, 0 AS UNIDDCO, 0 AS UNIDNCO, 0 AS UNIDDNC,
                 SUM(CASE WHEN (TIPOOPI='O') THEN IIF(ESUNID=1,CANTIDAD,0)
                          WHEN (TIPOOPI='T') THEN IIF(ESUNID=1,CANTIDAD,0)
                                ELSE 0 END) AS UNIDCAR,
                 SUM(CASE WHEN (TIPOOPI='P') THEN IIF(ESUNID=1,CANTIDAD,0)
                          WHEN (TIPOOPI='N') THEN IIF(ESUNID=1,CANTIDAD,0)
                                ELSE 0 END) AS UNIDDES,
                 SUM(IIF(TIPOOPI='Q',IIF(ESUNID=1,(CANTIDADD-CANTIDADUA),0),0)) AS UNIDAJU

            FROM SAITEMOPI
           WHERE (TIPOOPI IN ('N','O','P','Q','T'))  AND
                 (SUBSTRING(ISNULL(CODUBIC,''),1,LEN(+''))=+'')
           GROUP BY CODITEM, FECHAE) O
   WHERE (O.FECHAE>=CONVERT(DATETIME,'2023-11-01',120)) AND                            -- CAMBIO FECHAPER
         (O.FECHAE<=CONVERT(DATETIME,'2024-05-31',120))
   GROUP BY O.CODITEM, O.FECHAE
)
SELECT V.CODITEM,
       SUM(V.EXINICIAL) AS EXINICIAL, SUM(V.EXUNIDINI) AS EXUNIDINI,
       SUM(V.CANTVEN) AS CANTVEN, SUM(V.CANTDEV) AS CANTDEV, SUM(V.CANTNEV) AS CANTNEV, SUM(V.CANTDNV) AS CANTDNV,
       SUM(V.CANTCOM) AS CANTCOM, SUM(V.CANTDCO) AS CANTDCO, SUM(V.CANTNCO) AS CANTNCO, SUM(V.CANTDNC) AS CANTDNC,
       SUM(V.CANTCAR) AS CANTCAR, SUM(V.CANTDES) AS CANTDES, SUM(V.CANTAJU) AS CANTAJU,
       SUM( V.EXINICIAL
           -V.CANTVEN+V.CANTDEV-V.CANTNEV+V.CANTDNV
           +V.CANTCOM-V.CANTDCO+V.CANTNCO-V.CANTDNC
           +V.CANTCAR-V.CANTDES+V.CANTAJU) AS CANTFINAL,

       SUM(V.UNIDVEN) AS UNIDVEN, SUM(V.UNIDDEV) AS UNIDDEV, SUM(V.UNIDNEV) AS UNIDNEV, SUM(V.UNIDDNV) AS UNIDDNV,
       SUM(V.UNIDCOM) AS UNIDCOM, SUM(V.UNIDDCO) AS UNIDDCO, SUM(V.UNIDNCO) AS UNIDNCO, SUM(V.UNIDDNC) AS UNIDDNC,
       SUM(V.UNIDCAR) AS UNIDCAR, SUM(V.UNIDDES) AS UNIDDES, SUM(V.UNIDAJU) AS UNIDAJU,
       SUM( V.EXUNIDINI
           -V.UNIDVEN+V.UNIDDEV-V.UNIDNEV+V.UNIDDNV
           +V.UNIDCOM-V.UNIDDCO+V.UNIDNCO-V.UNIDDNC
           +V.UNIDCAR-V.UNIDDES+V.UNIDAJU) AS UNIDFINAL into ##Temp

  FROM (SELECT CODPROD AS CODITEM,
               SUM(EXINICIAL) AS EXINICIAL, SUM(EXUNDINI) AS EXUNIDINI,
               0 AS CANTVEN, 0 AS CANTDEV, 0 AS CANTNEV, 0 AS CANTDNV,
               0 AS CANTCOM, 0 AS CANTDCO, 0 AS CANTNCO, 0 AS CANTDNC,
               0 AS CANTCAR, 0 AS CANTDES, 0 AS CANTAJU,

               0 AS UNIDVEN, 0 AS UNIDDEV, 0 AS UNIDNEV, 0 AS UNIDDNV,
               0 AS UNIDCOM, 0 AS UNIDDCO, 0 AS UNIDNCO, 0 AS UNIDDNC,
               0 AS UNIDCAR, 0 AS UNIDDES, 0 AS UNIDAJU
          FROM SAINITI WITH (NOLOCK)
         WHERE (PERIODO+'01'=SUBSTRING(CONVERT(VARCHAR,CONVERT(DATETIME,'2023-11-01',120),112),1,8))     -- CAMBIO FECHAPER
         GROUP BY CODPROD
         UNION ALL
        SELECT CODITEM,
               0 AS EXINICIAL,                

               0 AS EXUNIDINI,

               0 AS CANTVEN, 0 AS CANTDEV, 0 AS CANTNEV, 0 AS CANTDNV,
               0 AS CANTCOM, 0 AS CANTDCO, 0 AS CANTNCO, 0 AS CANTDNC,
               0 AS CANTCAR, 0 AS CANTDES, 0 AS CANTAJU,

               0 AS UNIDVEN, 0 AS UNIDDEV, 0 AS UNIDNEV, 0 AS UNIDDNV,
               0 AS UNIDCOM, 0 AS UNIDDCO, 0 AS UNIDNCO, 0 AS UNIDDNC,
               0 AS UNIDCAR, 0 AS UNIDDES, 0 AS UNIDAJU

          FROM CALCINITINVENT WITH (NOLOCK)
         WHERE (FECHAE>=SUBSTRING(CONVERT(VARCHAR,CONVERT(DATETIME,'2023-11-01',120),112),1,8)) AND         
               (FECHAE< SUBSTRING(CONVERT(VARCHAR,CONVERT(DATETIME,'2024-05-31',120),112),1,8))             
         GROUP BY CODITEM
         UNION ALL
        SELECT CODITEM, 0 AS EXINICIAL, 0 AS EXUNIDINI,
               SUM(CANTVEN) AS CANTVEN, SUM(CANTDEV) AS CANTDEV, SUM(CANTNEV) AS CANTNEV, SUM(CANTDNV) AS CANTDNV,
               SUM(CANTCOM) AS CANTCOM, SUM(CANTDCO) AS CANTDCO, SUM(CANTNCO) AS CANTNCO, SUM(CANTDNC) AS CANTDNC,
               SUM(CANTCAR) AS CANTCAR, SUM(CANTDES) AS CANTDES, SUM(CANTAJU) AS CANTAJU,

               SUM(UNIDVEN) AS UNIDVEN, SUM(UNIDDEV) AS UNIDDEV, SUM(UNIDNEV) AS UNIDNEV, SUM(UNIDDNV) AS UNIDDNV,
               SUM(UNIDCOM) AS UNIDCOM, SUM(UNIDDCO) AS UNIDDCO, SUM(UNIDNCO) AS UNIDNCO, SUM(UNIDDNC) AS UNIDDNC,
               SUM(UNIDCAR) AS UNIDCAR, SUM(UNIDDES) AS UNIDDES, SUM(UNIDAJU) AS UNIDAJU

          FROM CALCINITINVENT WITH (NOLOCK)
         WHERE (FECHAE>=SUBSTRING(CONVERT(VARCHAR,CONVERT(DATETIME,'2023-11-01',120),112),1,8)) AND
               (FECHAE<=SUBSTRING(CONVERT(VARCHAR,CONVERT(DATETIME,'2024-05-31',120),112),1,8))
         GROUP BY CODITEM
       ) V
       INNER JOIN SAPROD P
          ON (P.CODPROD=V.CODITEM)
       INNER JOIN VW_ADM_INSTANCIAS I
          ON (P.CODINST=I.CODINST)
 WHERE (P.ESENSER=CONVERT(INT,0)) AND
       (('General'+''='GENERAL') OR (P.ESIMPORT=CHARINDEX(SUBSTRING('General'+'',1,1),'NI')-1)) AND  -- RASPA COCO
       (SUBSTRING(I.OrderByField,1,LEN(+''))=+'') AND
       (SUBSTRING(V.CODITEM,1,LEN(+''))>=+'') AND
       (SUBSTRING(V.CODITEM,1,LEN(+''))<=+'') AND
       EXISTS(SELECT CODITEM, CODPROV
                FROM (SELECT CODITEM, CODPROV
                        FROM SAPVPR
                       UNION
                      SELECT CODPROD, '' AS CODPROV
                        FROM SAPROD) PV
               WHERE (PV.CODITEM=V.CODITEM) AND (SUBSTRING(CODPROV,1,LEN(+''))=+'')) --and CodProd >= 'ALTG100' and CodProd<= 'ALTG100'
 GROUP BY V.CODITEM
HAVING SUM(V.CANTVEN)<>0 OR SUM(V.CANTDEV)<>0 OR SUM(V.CANTNEV)<>0 OR SUM(V.CANTDNV)<>0 OR
       SUM(V.CANTCOM)<>0 OR SUM(V.CANTDCO)<>0 OR SUM(V.CANTNCO)<>0 OR SUM(V.CANTDNC)<>0 OR
       SUM(V.CANTCAR)<>0 OR SUM(V.CANTDES)<>0 OR SUM(V.CANTAJU)<>0
 ORDER BY V.CODITEM


--update P 
--set t.CANTFINAL, p.Existen, t.CANTFINAL - p.Existen, *
-- from ##Temp t inner join SAPROD p on t.CODITEM = p.codprod
-- where p.Existen <>t.CANTFINAL

-- drop table  ##Temp

